.TH doctor 6
.SH NAME
doctor \- interact with a psychoanalyst
.SH SYNTAX
.B /usr/games/doctor
.SH DESCRIPTION
.I Doctor 
is a lisp-language version of the legendary ELIZA program.
This script "simulates" a Rogerian psychoanalyst.
Type in lower case, and when you get tired or bored, type 
your interrupt character (either control-C or Rubout). 
Remember to type two carriage returns when you want it to answer.
.PP
In order to run this you must have a Franz Lisp system in /usr/ucb/lisp.
