(File fpMacs.l)
(unitTreeInsert macro list quote cons cadr)
(treeIns macro quote list cadddr caddr cadr)
(twop macro quote list cadr)
(size macro cons quote list cadr)
(find macro cons quote list caddr cadr)
(Read macro quote)
(Getc macro quote)
(peekc macro quote)
(Tyi macro quote)
