(File fpPP.l)
(printAccross lambda go cdr setq nwritn car prDF null cond quote princ prog)
(prD1 lambda pntlen plus atom |1+| cdr setq null cond car prDF prog)
(prDF lambda go prD1 nwritn setq quote car atom $patom1 printAccross charcnt + <& print null let progn printRet dtpr not or tab return prDF patom terpri |1+| flatc cdr >& and cond prog)
(fpPP lambda prDF terpri)
(printRet macro cdr append cons quote list)
