(File handlers.l)
(break-resp lambda reset and null outfile setq resetio truename let cond terpr quote patom msg-tyo-char progn msg)
(undef-func-handler lambda cons ncons cxr getd return load get symbolp bottom cdddr patom terpr progn msg terpri null caddr cadr car list implode quote eq length greaterp not and cond explode nreverse caddddr setq prog)
(franz-reset lambda quote old-reset-function *throw errset setq)
(break-err-handler lexpr *throw lessp numberp cadr cons ncons or sub1 return eval exit status read *catch dtpr do caddr cdr car cdddr liszt-internal-do mapc print reset and null outfile resetio truename let quote msg-tyo-char patom terpr progn msg arg cadddr eq greaterp cond setq add1)
