# @(#)Makefile	1.1	Ultrix	7/3/86
#
#	Makefile for GNU Emacs "man" subdirectory.
#

# Symbol DESTROOT is derived from top level Makefile.
DESTROOT=

all:
	@echo ""
	@echo "\"man/Makefile all \" does nothing."
	@echo "	man directory has only the source of the Emacs manual."

install: 
	@echo ""
	@echo "\"man/Makefile install\" doesn't move anything"
	@echo "	to the target director."
	@echo "	man directory has only the source of the Emacs manual."

clean:

clobber:	clean
	sccs clean

sccsinfo:
	@sccs info

sccsget:
	sccs get SCCS

