#	1.2	Makefile	84/10/11
DESTROOT=
all:;

install:
	@install -c dsh.1 ${DESTROOT}/usr/new/doc/dsh.1

clean:;

clobber: clean
	@rm -f Makefile dsh.*

sccsget:
		@sccs get -s SCCS

sccsinfo:
		@sccs info
