.TH ustat 2
.SH NAME
ustat \- get file system statistics
.SH SYNTAX
.nf
.ft B
#include <sys/types.h>
#include <ustat.h>
.PP
.ft B
int ustat (dev, buf)
int dev;
struct ustat \(**buf;
.fi
.SH DESCRIPTION
The
.PN ustat
call
returns information about a mounted file system.
The
.I dev
argument is a device number identifying a device containing
a mounted file system.
The
.I buf
argument is a pointer to a
.PN ustat
structure that includes the following elements:
.EX
daddr_t  f_tfree;       /\(** Total free blocks (Kbytes) \(**/
ino_t    f_tinode;      /\(** Number of free inodes \(**/
char     f_fname[512];  /\(** Filsys name \(**/
char     f_fpack[6];    /\(** Filsys pack name \(**/
.EE
The 
.I f_fpack
always returns a null string.
.PP
.SH DIAGNOSTICS
The
.PN ustat
call will fail if one or more of the following are true:
.TP 15
.TP
.SM
\%[EINVAL]
The 
.I dev\^
argument is not the device number of a 
device containing a mounted file system.
.TP
.SM
\%[EFAULT]
The
.I buf\^
argument points outside the process's allocated address space.
.TP
[ETIMEDOUT]
A "connect" request or remote file operation failed
because the connected party
did not properly respond after a period
of time which is dependent on the communications protocol.
.SH SEE ALSO
stat(2), fs(5).
