.TH rd 4
.SH NAME
rd \- RD31, RD32, RD53, RD54 \- Small VAX winchester disks 
.SH DESCRIPTION
The RD Winchester disks when used either by the workstation
or multiuser configurations of the busless Small VAX processor
are supported by the SDC disk driver.
The SDC driver handles RD31, RD32, RD53 and RD54 disks on
drives 0 and 1.
.SH FILES
/dev/rd[0-1] [a-f]
.br
/dev/rrd[0-1] [a-f]
.SH SEE ALSO
sdc(4)
