.TH rx 4
.SH NAME
rx \- RX33 \-  Small VAX floppy disk drive
.SH DESCRIPTION
The RX33 floppy disk drive when used by either the workstation
or multiuser configurations of the busless Small VAX processor
is supported by the SDC disk driver.
The SDC driver handles the RX33 disk on
drive 2.
The RX33 floppy disk drive reads and writes both RX33 and RX50
floppy diskettes.
.SH FILES
/dev/rx2a
.br
/dev/rrx2a 
.SH SEE ALSO
sdc(4)
