!
! BOOTSTRAP ON HK, Diagnostic Supervisor
!
SET DEF HEX
SET DEF LONG
SET REL:0
HALT
UNJAM
INIT
LOAD BOOT
D R10 103	! DEVICE CHOICE 3=HK
D R11 60000010	! 10= Diagnostic Supervisor
START 2
