!
! BOOTSTRAP ON RA, Diagnostic Supervisor
!
SET DEF HEX
SET DEF LONG
SET REL:0
HALT
UNJAM
INIT
LOAD BOOT
D R10 209	! DEVICE CHOICE 9=RA
D R11 60000010	! 10= Diagnostic Supervisor
START 2
