.TH fold 1
.SH NAME
fold \- fold long lines for finite width output device
.SH SYNTAX
.B fold
[
\-width
] [
file ...
]
.SH DESCRIPTION
The
.B fold
command
is a filter which will fold the contents of the specified files,
or the standard input if no files are specified,
breaking the lines to have maximum width
.I width.
The default for
.I width
is 80.  The
.B width
should be a multiple of 8 if tabs are present, or the tabs should
be expanded using expand(1) before coming to
.I fold.
.SH RESTRICTIONS
If underlining is present it may be messed up by folding.
.SH SEE ALSO
expand(1)
