.\" Last modified by MJT on 26-Aug-85  23
.\"  Repaired beginning matter to work right in whatis database
.tr ~
.nr f 0
.de SP
.if n .ul
\%[\fB\-\\$1\fR\\c
.if n .ul 0
\\$2\\$3
..
.de SF
.if n .ul
\%[\fB\-\\$1\fR]
.if n .ul 0
..
.ds M)  \fB\s-1MR\s+1\fR
.ds R)  \fB\s-1RELEASE NUMBER\s+1\fR
.ds S)  SCCS
.\".ds S)  \s-1SCCS\s+1
.\".ds I)  \s-1SID\s+1
.ds I)  SID
.TH get 1
.SH NAME
get \- get a version of an SCCS file
.SH SYNTAX
.B get
.SP r \*(S) ]
.SP c cutoff ]
.SP i list ]
.SP x list ]
.SP a seq-no. ]
.SF k
.SF e
.if n .ul
[\-l[p]]
.if n .ul 0
.SF p
.SF m
.SF n
.SF s
.SF b
.SF g
.SF t
file
.B ".\|.\|."
.SH DESCRIPTION
The
.PN get
command generates an \s-1ascii\s+1 text file from
each named \*(S) file according to the specifications given
by its keyletter arguments,
which begin with \fB\-\fR.
The arguments
may be specified in any order,
but all keyletter arguments apply to all named \*(S) files.
If a directory is named,
.PN get
behaves as though each file in the directory were
specified as a named file,
except that non-\*(S) files
(last component of the path name does not begin with
.BR s. )
and unreadable files
are silently ignored.
If a name of \fB\-\fR is given, the standard input is read;
each line of the standard input is taken to be the name of an \*(S) file
to be processed.
Again, non-\*(S) files and unreadable files are silently ignored.
.PP
The generated text is normally written into a file called the
.I g-file
whose name is derived from the \*(S) file name by simply
removing the leading
\fBs.\fR;
(see also \fI\s-1FILES\s+1\fP, below).
.PP
Each of the keyletter arguments is explained below
as though only one \*(S) file is to be processed,
but the effects of any keyletter argument applies independently to
each named file.
.sp
Keyletter arguments
.TP "\w'\fB\-a\fIseq-no.\fR~~'u"
.BI \-r SID
The
.\".IR S "\s-1CCS\s+1 " ID entification
\s-2SCCS\s+2 identification
string (\*(I)) of the version (delta)
of an \*(S) file to be retrieved.
Table~1 below shows, for the most useful cases, what version
of an \*(S) file is retrieved (as well as the \*(I)
of the version to be eventually created by
.PN delta(1)
if the
.B \-e
keyletter is also used),
as a function of the \*(I) specified.
.TP
.BI \-c cutoff
\fICutoff\fR
date-time,
in the form:
.IP
	\s-1YY[MM[DD[HH[MM[SS]]]]]\s+1
.IP
No changes (deltas) to the \*(S) file which were created after
the specified \fIcutoff\fR date-time are included in the generated
\s-1ASCII\s+1 text file.
Units omitted from the date-time default
to their maximum possible values;
that is,
.B \-c7502
is equivalent to
.BR \-c750228235959 .
Any number of non-numeric characters may separate
the various two digit pieces of the \fIcutoff\fR date-time.
This feature allows one to specify a \fIcutoff\fR date in the form:
\&"\fB\-c77/2/2 9:22:25\fP".
.TP
.B \-e
Indicates
that the
.PN get
is for the purpose of editing or making a change
(delta) to the \*(S) file by a subsequent use of 
.PN delta(1).
The
.B \-e
keyletter used in a
.PN get
for a particular version (\*(I)) of the \*(S) file prevents
further
.PN gets
from editing on the same \*(I) until
.PN delta
is executed or the
.B j
(joint edit) flag is set in the \*(S) file,
see
.PN admin(1).
Concurrent use of
.PNB get \-e
for different \*(I)s is always allowed.
If the SCCS front end processor is used,
the command
.PNB get \-e
is replaced by
.B edit.
.IP
If the
.I g-file
generated by
.PN get
with an
.B \-e
keyletter is accidentally ruined while being edited,  
it may be regenerated by re-executing the
.PN get
command with the
.B \-k
keyletter
in place of the \fB\-e\fP keyletter.
.IP
.SM SCCS
file protection specified by the
ceiling, floor, and authorized user list
stored in the \*(S) file
are enforced when the
.B \-e
keyletter is used.
For further information, see 
.PN admin(1).
.TP
.B \-b
Used
with the
.B \-e
keyletter to indicate that the new delta
should have an \*(I) in a new branch
as shown in Table~1.
This keyletter is ignored if the
.B b
flag is not present in the file
or if the retrieved
delta is not a leaf delta.
For further information, see 
.PN admin(1).
A leaf delta is one that has no successors on
the \*(S) file tree.
.NT
A branch delta may always be 
created from a nonleaf delta.
.NE
.TP
.BI \-i list
A
\fIlist\fR of deltas to be included
(forced to be applied)
in the creation of the generated file.
The \fIlist\fR has the following syntax:
.IP
	<list> ::= <range> \(or <list> , <range>
.br
	<range> ::= \*(I) \(or \*(I) \- \*(I)
.IP
\*(I), may
be in any form shown in the '\*(I) Specified' column of
Table~1.
Partial \*(I)s are interpreted as shown in the '\*(I) Retrieved'
column of Table~1.
.TP
.BI \-x list
A
\fIlist\fR of deltas to be excluded
(forced not to be applied)
in the creation of the generated file.
See the
.B \-i
keyletter for the \fIlist\fR format.
.TP
.B \-k
Suppresses
replacement of identification keywords
in the retrieved text
by their value.
The
.B \-k
keyletter
is implied by the
.B \-e
keyletter.
.TP
.BR \-l [ p ]
Causes
a delta
summary to be written into an
\fIl-file.\fR
If
.B \-lp
is used
then an
.I l-file
is not created;
the delta summary is written on the standard output instead.
See \fB\s-1FILES\s+1\fP for the format of the
\fIl-file.\fR
.TP
.B \-p
Causes
the text retrieved
from the \*(S) file to
be written on the standard output.
No
.I g-file
is created.
All output which normally goes to the standard output
goes to file descriptor 2 instead,
unless the
.B \-s
keyletter is used,
in which case it disappears.
.TP
.B \-s
Suppresses
all output normally written on the
standard output.
However,
fatal error messages, which always go to file descriptor
2, remain unaffected.
.TP
.B \-m
Causes
each text line retrieved from the \*(S) file
to be preceded by the
\*(I)
of the delta that inserted the text line in the \*(S) file.
The format is:
\*(I),
followed by a horizontal tab, followed by the text line.
.TP
.B \-n
Causes
each generated text line to be preceded with the
%\&M\&% identification keyword value
(see below).
The format is:
%\&M\&% value,
followed by a horizontal tab,
followed by the text line.
When both the
.B \-m
and
.B \-n
keyletters are used,
the format is:
%\&M\&% value,
followed by a horizontal tab,
followed by the
.B \-m
keyletter generated format.
.TP
.B \-g
Suppresses
the actual retrieval of text from the \*(S) file.
It is primarily used to generate an
\fIl-file\fR,
or to verify the existence of a particular \*(I).
.TP
.B \-t
Used
to access the most recently created
('top')
delta in a given release,
for example,
.BR \-r1 ),
or
release and level,
for example,
.BR \-r1.2 ).
.TP
.BI \-a "seq-no."
The
delta sequence number of the \*(S) file delta (version) to be retrieved.
For further information, see sccsfile(5).
This keyletter is used by the
comb(1) command.
It is not a generally useful keyletter,
and users should not use it.
If both the
.B \-r
and
.B \-a
keyletters are specified,
the
.B \-a
keyletter is used.
Care should be taken when using the
.B \-a
keyletter in conjunction with the
.B \-e
keyletter,
as the \*(I) of the delta to be created
may not be what one expects.
The
.B \-r
keyletter can be used with the
.B \-a
and
.B \-e
keyletters to control the naming of the \*(I) of the delta to
be created.
.i0
.PP
For each file processed,
.PN get
responds (on the standard output) with the
\*(I)
being accessed and
with the number of lines retrieved from the \*(S) file.
.PP
If the
.B \-e
keyletter is used, the
\*(I)
of the delta to be made appears
after the
\*(I)
accessed and before the number of lines generated.
If there is more than one named file
or if a directory or standard input is named,
each file name is printed
(preceded by a new-line)
before it is processed.
If the
.B \-i
keyletter is used included deltas are listed following the
notation 'Included';
if the
.B \-x
keyletter is used, excluded deltas are listed following the
notation 'Excluded'.
.ne 10v
.PP
.in 0
.TS
center ;
c s s s s
c1 c1 c1 c1 c0
c c c c c
l c l l l .
TABLE 1. Determination of \s-1SCCS\s+1 Identification String
.sp 1.5p
\s-1SID\s+1*	\fB\-b\fP Keyletter	Other	\s-1SID\s+1	\s-1SID\s+1 of Delta
Specified	Used\(dg	Conditions	Retrieved	to be Created

none\(dd	no	R defaults to mR	mR.mL	mR.(mL\^+1)
.sp .5
none\(dd	yes	R defaults to mR	mR.mL	mR.mL.(mB\^+1).1
.sp 1.5p
R	no	R > mR	mR.mL	R.1***
.sp .5
R	no	R = mR	mR.mL	mR.(mL\^+1)
.sp .5
R	yes	R > mR	mR.mL	mR.mL.(mB\^+1).1
.sp .5
R	yes	R = mR	mR.mL	mR.mL.(mB\^+1).1
.sp .5
R	\-	R < mR and	hR.mL**	hR.mL.(mB\^+1).1
\^	\^	R does \fInot\fP exist	\^	\^
.sp .5
R	\-	Trunk succ.#	R.mL	R.mL.(mB\^+1).1
\^	\^	in release > R	\^	\^
\^	\^	and R exists	\^	\^
.sp .5
R.L	no	No trunk succ.	R.L	R.(L\^+1)
.sp .5
R.L	yes	No trunk succ.	R.L	R.L.(mB\^+1).1
.sp .5
R.L	\-	Trunk succ.	R.L	R.L.(mB\^+1).1
\^	\^	in release \(>= R	\^	\^
.sp .5
R.L.B	no	No branch succ.	R.L.B.mS	R.L.B.(mS\^+1)
.sp .5
R.L.B	yes	No branch succ.	R.L.B.mS	R.L.(mB\^+1).1
.sp .5
R.L.B.S	no	No branch succ.	R.L.B.S	R.L.B.(S\^+1)
.sp .5
R.L.B.S	yes	No branch succ.	R.L.B.S	R.L.(mB\^+1).1
.sp .5
R.L.B.S	\-	Branch succ.	R.L.B.S	R.L.(mB\^+1).1
.sp .5
_
.TE
.in \n(INu
.PP
.PD 0
.TP "\w@***\ \ \ @u"
*
R, L, B, and S are the release, level,
branch, and sequence components of the \s-1SID\s+1, 
in that order;
m means maximum.
Thus, for example, R.mL means the maximum
level number within release R;
R.L.(mB+1).1 means
the first sequence number on the
new branch (that is, maximum branch number plus
one) of level L within release R.
Note that if the \s-1SID\s+1 specified is of the form R.L,
R.L.B, or R.L.B.S, each of the
specified components must exist.
.TP
**
hR is the highest
existing release that is lower than
the specified, nonexistent, release\ R.
.TP
***
This is used to force creation of the
first delta in a new release.
.TP
#
Successor.
.TP
\(dg
The
.B \-b
keyletter is effective only if the
.B b
flag 
is present in the file.
An entry of \fB\-\fR means 'irrelevant'.
For further information, see 
.PN admin(1).
.TP
\(dd
This case applies if the
.B d
(default SID) flag is not present in the file.  If the
.B d
flag is present in the file, then the
SID obtained from the
.B d
flag is interpreted as if it had been specified on the command line.
Thus, one of the other cases in this table applies.
.PD
.SH IDENTIFICATION KEYWORDS
Identifying information
is inserted into the text retrieved from the \*(S) file by replacing
identification keywords
with their value wherever they occur.
The following keywords may be used in the text stored in an \*(S) file:
.br
.ne 5v
.PP
.PD 0
.TP "\w'Keyword~~~'u"
.I Keyword
.I Value
.TP
.B %\&M\&%
Module name:
either the value of the
.B m
flag in the file
or if absent,
the name of the \*(S) file with the
leading
.B s.
removed.
For further information, see 
.PN admin(1).
.TP
.B %\&I\&%
\*(S) identification (\*(I)) (%\&R\&%.%\&L\&%.%\&B\&%.%\&S\&%) of the retrieved text.
.TP
.B %\&R\&%
Release.
.TP
.B %\&L\&%
Level.
.TP
.B %\&B\&%
Branch.
.TP
.B %\&S\&%
Sequence.
.TP
.B %\&D\&%
Current date (\s-1YY/MM/DD\s+1).
.TP
.B %\&H\&%
Current date (\s-1MM/DD/YY\s+1).
.TP
.B %\&T\&%
Current time (\s-1HH:MM:SS\s+1).
.TP
.B %\&E\&%
Date newest applied delta was created (\s-1YY/MM/DD\s+1).
.TP
.B %\&G\&%
Date newest applied delta was created (\s-1MM/DD/YY\s+1).
.TP
.B %\&U\&%
The time the newest applied delta was created (\s-1HH:MM:SS\s+1).
.TP
.B %\&Y\&%
Module type:
value of the
.B t
flag in the \*(S) file
For further information, see 
.PN admin(1).
.TP
.B %\&F\&%
\*(S) file name.
.TP
.B %\&P\&%
Fully qualified \*(S) file name.
.TP
.B %\&Q\&%
The
value of the
.B q
flag in the file
For further information, see 
.PN admin(1).
.TP
.B %\&C\&%
Current line number.
This keyword is intended for identifying output program messages
such as 'this shouldn't have happened' type errors.
It is not intended to be used on every line to provide
sequence numbers.
.TP
.B %\&Z\&%
The 4-character string \fB@(#)\fR
recognizable by
.PN what(1).
.TP
.B %\&W\&%
A shorthand notation for constructing
.PN what(1)
strings
for \s-1UNIX\s+1 program files.
%\&W\&%~=~%\&Z\&%%\&M\&%<horizontal-tab>%\&I\&%
.TP
.B %\&A\&%
Another shorthand notation for constructing
.PN what(1)
strings
for non-\s-1UNIX\s+1 program files.
%\&A\&%~=~%\&Z\&%%\&Y\&%~%\&M\&%~%\&I\&%%\&Z\&%
.PD
.SH RESTRICTIONS
If the user has
write permission in the directory
containing the 
.I g-files,
but the real user doesn't,
then only one file can be named when the
.B \-e
keyletter is used.
.SH DIAGNOSTICS
See
.PN sccshelp(1) 
for explanations.
.SH FILES
Several auxiliary files may be created by
.PN get,
These files are known generically as the
\fIg-file, l-file, p-file,\fR
and
\fIz-file\fR.
The letter before the hyphen is called the tag.
An auxiliary file name is formed from the \*(S) file name:
the last component of
all \*(S) file names must be of the form \fBs.\fP\fImodule-name\fP,
the auxiliary files are named by replacing the leading \fBs\fR
with the tag.
The
.I g-file
is an exception to this scheme:
the
.I g-file
is named by removing
the
.B s.
prefix.
For example,
.BR s.xyz.c ,
the auxiliary file names would be
.BR xyz.c ,
.BR l.xyz.c ,
.BR p.xyz.c ,
and
.BR z.xyz.c ,
respectively.
.PP
The
\fIg-file\fR,
which contains the generated text,
is created
in the current directory
(unless the
.B \-p
keyletter is used).
A
.I g-file
is created in all cases, whether or not any lines of text
were generated by the
.PN get.
It is owned by the real user.
If the
.B \-k
keyletter is used or implied its mode is 644;
otherwise its mode is 444.
Only the real user need have
write permission in the current
directory.
.PP
The
.I l-file
contains
a table showing which deltas were applied
in generating the retrieved text.
The
.I l-file
is created
in the current directory
if the
.B \-l
keyletter is used;
its mode is 444 and it is owned by the real user.
Only the real user need have
write permission in the
current directory.
.PP
Lines in the
.I l-file
have the following format:
.PP
.PD 0
.RS
.nr a 0 1
.af a a
.TP
\n+a.
A blank character if the delta was applied;
.br
\fB\(**\fR otherwise.
.TP
\n+a.
A blank character if the delta was applied or wasn't applied and ignored;
.br
\fB\(**\fR if the delta wasn't applied and wasn't ignored.
.TP
\n+a.
A code indicating a 'special' reason
why the delta was or was not applied:
.RS 10
\'I': Included.
.br
\'X': Excluded.
.br
\'C': Cut off (by a
.B \-c
keyletter).
.RE
.TP
\n+a.
Blank.
.TP
\n+a.
\*(S) identification (\*(I)).
.TP
\n+a.
Tab character.
.TP
\n+a.
Date and time (in the form
\s-1YY/MM/DD~HH:MM:SS\s+1)
of creation.
.TP
\n+a.
Blank.
.TP
\n+a.
Login name of person who created delta.
.PD
.RE
.IP
The
comments and \*(M) data follow on subsequent lines,
indented one horizontal tab character.
A blank line terminates each entry.
.PP
The
.I p-file
is used to
pass information resulting from a
.PN get
with an
.B \-e
keyletter along to
delta.
Its contents are also used to prevent a subsequent
execution of
.PN get
with an
.B \-e
keyletter
for the same \*(I) until delta
is executed or the joint edit flag,
.BR j ,
see
.PN admin(1),
is set in the \*(S) file.
The
.I p-file
is created in the directory containing the \*(S) file
and the effective user must have
write permission
in that directory.
Its mode is 644 and it is owned by the effective user.
The format of the
.I p-file
is:
the gotten \*(I),
followed by a blank,
followed by the \*(I) that the new delta will have when it is made,
followed by a blank,
followed by the login name of the real user,
followed by a blank,
followed by the date-time
the
.PN get
was executed,
followed by a blank and the
.B \-i
keyletter argument if it was present,
followed by a blank and the
.B \-x
keyletter argument if it was present,
followed by a new-line.
There can be an arbitrary number of lines in the
.I p-file
at any time;
no two lines can have the same new delta \*(I).
.PP
The
.I z-file
serves as a
.I lock-out
mechanism against simultaneous updates.
Its contents are
the binary (two bytes) process \s-1ID\s+1 of the
command
.PN get
that created it.
The
.I z-file
is created in the directory containing the \*(S) file for the duration of 
.PN get.
The same protection restrictions for the
.I p-file
apply for the
\fIz-file\fR.
The
.I z-file
is
created mode 444.
.SH "SEE ALSO"
admin(1), delta(1), prs(1), sccs(1), sccsfile(5), sccshelp(1),
what(1)
.br
System Management Guide
