.TH newaliases 1
.SH NAME
newaliases \- rebuild the data base for the mail aliases file
.SH SYNTAX
.B newaliases
.SH DESCRIPTION
The
.B newaliases
command rebuilds the random access data base for the mail aliases file
/usr/lib/aliases.
It must be run each time /usr/lib/aliases
is changed in order for the change to take effect.
.SH SEE ALSO
aliases(5), sendmail(8)
