.TH printenv 1
.SH NAME
printenv \- print out the environment
.SH SYNTAX
.B printenv
[ name ]
.SH DESCRIPTION
The
.B printenv
command
prints out the values of the variables in the environment.  If a
.I name
is specified, only its value is printed.
.PP
If a
.I name
is specified and it is not defined in the environment,
.B printenv
returns exit status 1, else it returns status 0.
.SH SEE ALSO
csh(1), environ(7), sh(1)
