.TH tabs 1 
.SH NAME
tabs \- set terminal tabs
.SH SYNTAX
.B tabs
[
.B \-n
] [
terminal
]
.SH DESCRIPTION
The
.B tabs
command
sets the tabs on a variety of terminals.
Various terminal names given in term(7)
are recognized;
the default is, however, suitable for most 300
baud terminals.
If the
.B \-n
flag is present then the left
margin is not indented as is normal.
.SH SEE ALSO
stty(1), term(7)
