.\" Last modified by MJT on 26-Aug-85  2324
.\"  Repaired beginning matter to work right in whatis database
.TH users 1
.SH NAME
users \- compact list of users who are on the system
.SH SYNTAX
.B users
.SH DESCRIPTION
The
.B users
command
lists the login names of the users currently on the system in a compact,
one-line format.
.SH FILES
/etc/utmp
.SH SEE ALSO
who(1)
