.TH 2780d 8
.SH NAME
2780d \- IBM 2780/3780 RJE emulator daemon
.SH SYNTAX
.B 2780d
.SH DESCRIPTION
The
.PN 2780d
program
is automatically executed when a user runs
2780e(1) or 3780e(1).
Once executed, 
.PN 2780d 
transmits
all data files (df*) in /usr/spool/rje
which have associated control files (cf*),
to the IBM system.
.PP
Two users executing
.PN 2780e(3780e)
do not cause two daemons to run.
The first one executed handles both
transmissions.
The daemon's process id is kept in /usr/spool/rje/.rjed .
Each time a daemon is run, it checks that file to see if an active
daemon is running and exits if one is.
.PP
If
.PN 2780d
has trouble accessing files, the system manager
should clean up the spool directory by removing any 
outdated received files or data files which are not
associated with a corresponding
control file.
.PP
The 
.PN "2780d"
program may become disabled when:
the call to the IBM system has not been completed within one minute,
the IBM system has gone down during transmission,
the /usr/spool/rje/.rjed file can not be read,
there has been an error in sending or receiving.
.PP
To re-establish the connection to the IBM system,
restart the daemon by typing
.PN "2780d"
on the command line.
.PP
When files are received from the IBM system, 
.PN 2780d
places them in /usr/spool/rje/rjetemp.out.
If your username is included in the job control statements, 
the files are given
a file name with the form
.I "rjedaytime"
and placed in your home directory.
If your username is not included, the
files are placed
in /usr/spool/rje.
If there are problems in renaming the files, they remain in
/usr/spool/rje/rjetemp.out.
.PP
To obtain a log of all files that are sent and received the
system manager must create
/usr/spool/rje/acctlog.
Once created, this file will list each file transmission.
Errors are logged in /usr/adm/rjelog.
.SH FILES
/usr/spool/rje/.rjed - process identification file
.br
/usr/spool/rje/cf* - control file
.br
/usr/spool/rje/df* - data file
.br
/usr/spool/rje/zf* - renamed control file
.br
/usr/spool/rje/acctlog - file transmission log file
.br
/usr/adm/rjelog - error log file
.SH SEE ALSO
2780e(1), 3780e(1)
