.TH intro 8
.SH NAME
intro \- introduction to system maintenance and operation commands
.SH DESCRIPTION
This section contains information related to system operation
and maintenance.  In particular, commands used to create new file
systems,
.IR newfs ,
.IR mkfs ,
and verify the integrity of the file systems,
.IR fsck ,
.IR icheck ,
.IR dcheck ,
and
.I ncheck
are described
here.  The section 
.I format
should be consulted when formatting disk packs.  The section
.I crash
should be consulted in understanding how to interpret system
crash dumps.
