#	1.2	Makefile	84/10/11
DESTROOT=
all:;

install: all
	@install -c hyroute.8 ${DESTROOT}/usr/new/doc/hyroute.n

clean:;

clobber: clean
	@rm -f Makefile hy*.*

sccsget:
		@sccs get -s SCCS

sccsinfo:
		@sccs info
