.\" Modified by MJT on 23-Apr-85  1623
.\"
.TH getpwent 3 
.SH NAME
getpwent, getpwuid, getpwnam, setpwent, endpwent \- get password file entry
.SH SYNTAX
.nf
.B #include <pwd.h>
.PP
.B struct passwd *getpwent()
.PP
.B struct passwd *getpwuid(uid)
.B int uid;
.PP
.B struct passwd *getpwnam(name)
.B char *name;
.PP
.B int setpwent()
.PP
.B int endpwent()
.fi
.SH DESCRIPTION
The routines,
.PN getpwent,
.PN getpwuid
and
.PN getpwnam,
each return a pointer to an object with the
following structure
containing the broken-out
fields of a line in the password file:
.EX

struct  passwd { /* see getpwent(3) */
        char    *pw_name;
        char    *pw_passwd;
        int     pw_uid;
        int     pw_gid;
        int     pw_quota;
        char    *pw_comment;
        char    *pw_gecos;
        char    *pw_dir;
        char    *pw_shell;
};

struct passwd *getpwent(), *getpwuid(), *getpwnam();
.EE
.PP
The fields
.I pw_quota
and
.I pw_comment
are unused; the others have meanings described in
passwd(5yp).
.PP
The
.PN getpwent
routine reads the next
line (opening the file if necessary);
The
.PN setpwent
subroutine rewinds the file.
The
.PN endpwent
subroutine closes it.
.PP
The
.PN getpwuid
and
.PN getpwnam
routines search from the beginning until a matching
.I uid
or
.I name
is found
(or until EOF is encountered).
.SH RESTRICTIONS
All information
is contained in a static area
so it must be copied if it is
to be saved.
.PP
If YP is running, 
.PN getgrent
does not return the entries in any particular order.
.SH DIAGNOSTICS
Null pointer
(0) returned on EOF or error.
.SH FILES
/etc/passwd
.SH "SEE ALSO"
getgrent(3), getlogin(3), ypclnt(3yp), passwd(5yp)
