.TH swab 3 
.SH NAME
swab \- swap bytes
.SH SYNTAX
.nf
.B swab(from, to, nbytes)
.B char *from, *to;
.fi
.SH DESCRIPTION
The
.PN swab
subroutine copies
.I nbytes
bytes pointed to by
.I from
to the position pointed to by
.I to,
exchanging adjacent even and odd bytes.
It is useful for carrying binary data between
PDP11's and other machines.  The
.I nbytes
should be even.
