.TH utime 3
.SH NAME
utime \- set file times
.SH SYNTAX
.nf
.B #include <sys/types.h>
.PP
.B utime(file, timep)
.B char *file;
.B time_t timep[2];
.fi
.SH DESCRIPTION
This interface has been superseded by utimes(2).
.PP
The
.PN utime
call
uses the
`accessed' and `updated' times in that order
from the
.I timep
vector
to set the corresponding recorded times for
.IR file .
.PP
The caller must be the owner of the file or the super-user.
The `inode-changed' time of the file is set to the current time.
.SH SEE ALSO
utimes(2), stat(2)
