#	1.3	Makefile	84/10/11
DESTROOT=
TARGET=/usr/new/doc
all:;

install:
	@install -c cpm.1 ${DESTROOT}${TARGET}/cpm.1

clean:;
clobber: clean
	@rm -f Makefile cpm.*	

sccsget:
		@sccs get -s SCCS

sccsinfo:
		@sccs info
